apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  labels:
    app: upload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload
  strategy:
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: vatsaldock/upload
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: upload-configmap
            - secretRef:
                name: upload-secret
