apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.minikube.internal:5432/auth"
  SPRING_DATASOURCE_USERNAME: "vatsal"
  SPRING_DATASOURCE_DB: "auth"