apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  RABBITMQ_EXCHANGE_NAME: video-exchange
  RABBITMQ_AUDIO_QUEUE_NAME: audio.queue
  RABBITMQ_AUDIO_ROUTING_KEY: audio.tracking
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  GMAIL_EMAIL: test.forvatsal@gmail.com